'use client';
import {useState} from 'react';
import {Plus,Radio,Trash2,ExternalLink} from 'lucide-react';
import {Source} from '@/lib/model';
export function Sources({sources,mutate}:{sources:Source[];mutate:(body:object)=>Promise<boolean>}){
 const [mode,setMode]=useState('url'),[adding,setAdding]=useState(false),[category,setCategory]=useState('Bangladesh'),[company,setCompany]=useState(''),[url,setUrl]=useState('');
 return <><div className="panel"><h2>Add Career Page</h2><p>Paste a company career URL. Job Assistant detects Greenhouse, Lever, and Ashby boards before trying an enabled HTML fallback.</p><div className="tabs"><button className={mode==='url'?'selected':''} onClick={()=>setMode('url')}>Career URL</button><button className={mode==='api'?'selected':''} onClick={()=>setMode('api')}>Direct API board</button></div><form onSubmit={async e=>{e.preventDefault();setAdding(true);const f=new FormData(e.currentTarget);try{const ok=await mutate({action:'source',company,category,country:category==='Bangladesh'?'Bangladesh':'Global',...(mode==='url'?{url,htmlAllowed:f.get('htmlAllowed')==='on'}:{provider:f.get('provider'),board:f.get('board')})});if(ok){setCompany('');setUrl('');}}finally{setAdding(false);}}}><div className="source-form"><input name="company" placeholder="Company / source name" aria-label="Company or source name" value={company} onChange={e=>setCompany(e.target.value)} required/><select aria-label="Source category" value={category} onChange={e=>setCategory(e.target.value)}><option>Bangladesh</option><option>Global</option></select>{mode==='url'?<input type="url" name="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://company.com/careers" aria-label="Career page URL" required/>:<><select name="provider" aria-label="Provider"><option>Greenhouse</option><option>Lever</option><option>Ashby</option><option>Adzuna</option></select><input name="board" placeholder="Board slug / Adzuna country (gb)" aria-label="Board slug or country code" pattern="[a-zA-Z0-9_-]+" required/></>}<button className="primary" disabled={adding}><Plus size={16}/>{adding?'Detecting source…':'Add source'}</button></div>{mode==='url'&&<label className="html-option"><input type="checkbox" name="htmlAllowed"/>Enable HTML collection for this page (only if the website permits it).</label>}</form><p>{mode==='url'?'HTML support includes JobPosting structured data and Cefalo/Vivasoft job pages. Unsupported pages stay on your watchlist with an explanation. Source category does not override a job’s actual location.':'Adzuna requires ADZUNA_APP_ID and ADZUNA_APP_KEY in .env.local and a supported country code, such as gb, us, de, or sg. It does not provide a Bangladesh feed. Fetches the first 50 software-engineer results per sync.'}</p></div>
 <div className="panel"><h2>Bangladesh career watchlist</h2><p>Start with the companies you already follow. Select one to fill the form, then add it.</p><div className="watchlist">{[['BRAC IT','https://www.bracits.com/career/?job__category_spec=engineering'],['Optimizely','https://careers.optimizely.com/search/?q=Senior+Software+Engineer&locationsearch=Dhaka&title=Senior'],['WSD (Development · Dhaka)','https://www.wsd.com/company/careers'],['Cefalo','https://career.cefalo.com/'],['Vivasoft','https://vivasoftltd.com/career/'],['Tekarsh','https://tekarsh.com/career'],['Field Nation','https://jobs.lever.co/fieldnation']].map(([name,link])=><button key={name} onClick={()=>{setMode('url');setCompany(name);setUrl(link);setCategory('Bangladesh');}}><Plus size={14}/>{name}</button>)}</div><p><a href="https://bdjobs.com/" target="_blank" rel="noopener noreferrer">Browse Bdjobs ↗</a> · Automated Bdjobs collection is not connected; a permitted API or feed is needed.</p></div>
 <div className="panel"><h2>Global career watchlist</h2><p>Track Front End and Full Stack openings across Agoda’s locations. Review each listing for relocation and eligibility terms.</p><div className="watchlist"><button onClick={()=>{setMode('url');setCompany('Agoda');setUrl('https://careersatagoda.com/vacancies/?keyword=Front+End&country=');setCategory('Global');}}><Plus size={14}/>Agoda · Front End + Full Stack</button></div></div>
 {(['Bangladesh','Global'] as const).map(group=><section key={group}><h2 className="source-group-heading">{group==='Bangladesh'?'Bangladesh sources':'Global sources'} <span>{sources.filter(s=>(s.category||'Global')===group).length}</span></h2>{sources.filter(s=>(s.category||'Global')===group).map(s=><div className="source-row panel" key={s.id}><span className="company-icon"><Radio/></span><div className="source-info"><h3>{s.company} <span className="status-tag">{s.enabled===false?'Paused':s.provider==='Unsupported'?'Needs setup':s.provider}</span></h3>{s.url&&<a className="source-link" href={s.url} target="_blank" rel="noopener noreferrer">{s.url}<ExternalLink size={12}/></a>}<p>{s.board||s.provider} · {s.lastSync?`Synced ${new Date(s.lastSync).toLocaleString()} · ${s.lastCount??'—'} engineering roles`:'Not synced yet'}</p>{s.detection&&<p>{s.detection}</p>}{s.error&&<p className="error">{s.error}</p>}</div><div className="source-actions"><button onClick={()=>mutate({action:'toggleSource',id:s.id})}>{s.enabled===false?'Enable':'Pause'}</button><button aria-label={`Remove ${s.company}`} onClick={()=>mutate({action:'deleteSource',id:s.id})}><Trash2 size={18}/></button></div></div>)}</section>)}
 {!sources.length&&<div className="empty"><Radio size={34}/><h3>Your watchlist is ready to grow</h3><p>Add a career URL or public API board above, then click Sync jobs.</p></div>}</>;
}
