import test from 'node:test';
import assert from 'node:assert/strict';
import {careerDeadline,parseEngineeringCareer,collectEngineeringCareer} from './collect';
import {detectSource,validateSource} from './sources';
const now=Date.parse('2026-09-14T00:00:00+06:00');
const source=()=>detectSource(validateSource({company:'BRAC IT',url:'http://bracits.com/career/?job__category_spec=engineering'}));
function page(deadline='15 Sep 2026'){return `<select class="awsm-job-category-filter-option"><option selected data-slug="engineering">Engineering</option></select><div class="awsm-job-listings"><div class="awsm-job-listing-item"><a class="awsm-job-item" href="https://www.bracits.com/jobs/database-admin/"><h2 class="awsm-job-post-title">Senior Database Administrator</h2></a><div class="awsm-job-specification-job-location"><span class="awsm-job-specification-term">Dhaka</span></div><div class="awsm-job-specification-deadline"><span class="awsm-job-specification-term">${deadline}</span></div></div></div>`;}
test('BRAC IT HTTP career URL upgrades to HTTPS with engineering scope',async()=>{const s=await source();assert.equal(s.board,'bracit-engineering');assert.match(s.url!,/^https:/);assert.equal(s.category,'Bangladesh');assert.throws(()=>validateSource({company:'Other',url:'http://example.com/career/'}));});
test('deadline includes the full final day in Bangladesh',()=>{assert.equal(careerDeadline('15 September 2026'),Date.parse('2026-09-15T23:59:59.999+06:00'));assert.throws(()=>careerDeadline('31 February 2026'));});
test('Engineering category includes database roles and skips expired jobs',()=>{assert.equal(parseEngineeringCareer(page(),now)[0].title,'Senior Database Administrator');assert.equal(parseEngineeringCareer(page('30 August 2026'),now).length,0);});
test('missing category or malformed layout fails visibly',()=>{assert.throws(()=>parseEngineeringCareer(page().replace('data-slug="engineering"','data-slug="sales"'),now),/filter/);assert.throws(()=>parseEngineeringCareer('<html>Error</html>',now),/layout/);});
test('BRAC IT detail normalization preserves original link and schema publication date',async()=>{const s=await source();const schema={'@type':'JobPosting',title:'Senior Database Administrator',description:'<h2>Department:</h2><h2>Engineering</h2><h2>Deadline:</h2><h2>15 September 2026</h2><p>Docker</p>',datePosted:'2026-08-20T18:12:34+06:00',jobLocation:{address:'Dhaka'}};const jobs=await collectEngineeringCareer(s,async url=>url.includes('/career/')?page():`<script type="application/ld+json">${JSON.stringify(schema)}</script>`,now);assert.equal(jobs.length,1);assert.equal(jobs[0].location,'Dhaka');assert.equal(jobs[0].posted,new Date(schema.datePosted).toISOString());assert.ok(jobs[0].skills.includes('Docker'));});
