import test from 'node:test';
import assert from 'node:assert/strict';
import {careerUrl,publicAddress} from './safe-fetch';
import {detectATS,embeddedATS,validateSource} from './sources';
import {companyLinks,normalize,structuredJobs,collect} from './collect';
const source=validateSource({company:'Example',category:'Bangladesh',url:'https://example.com/careers#jobs'});
test('detects ATS URLs and rejects lookalike hosts',()=>{assert.equal(detectATS('https://jobs.ashbyhq.com/example/123')?.board,'example');assert.equal(detectATS('https://jobs.eu.lever.co/example')?.region,'eu');assert.equal(detectATS('https://boards.greenhouse.io/embed/job_board?for=example')?.board,'example');assert.equal(detectATS('https://jobs.lever.co.attacker.com/example'),null);});
test('detects embedded ATS without arbitrary script execution',()=>assert.equal(embeddedATS('<iframe src="https://jobs.lever.co/example"></iframe>','https://example.com')?.provider,'Lever'));
test('rejects unsafe destinations',()=>{for(const u of ['http://example.com','https://localhost','https://127.0.0.1','https://[::1]','https://example.com:8080','https://user:pass@example.com'])assert.throws(()=>careerUrl(u));for(const ip of ['127.0.0.1','10.2.3.4','192.168.1.1','172.16.1.2','169.254.169.254','100.64.0.1','0.0.0.0','::1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('8.8.8.8'),true);});
test('career registration preserves category without changing job location',()=>{assert.equal(source.category,'Bangladesh');assert.equal(source.url,'https://example.com/careers');assert.equal(normalize(source,{title:'Engineer',location:'New York',description:'React'}).location,'New York');});
test('structured parser handles arrays and graphs without inventing jobs',()=>{const jobs=structuredJobs('<script type="application/ld+json">{"@graph":[{"@type":"Organization"},{"@type":"JobPosting","title":"Senior Engineer"}]}</script>');assert.equal(jobs.length,1);assert.equal(jobs[0].title,'Senior Engineer');assert.equal(structuredJobs('<h2>Our engineer testimonials</h2>').length,0);});
test('company parsers restrict discovery to job detail URLs and deduplicate',()=>{assert.deepEqual(companyLinks('<a href="/job/senior">Job</a><a href="/job/senior">Job</a><a href="/open-application">Other</a>','https://career.cefalo.com/'),['https://career.cefalo.com/job/senior']);assert.deepEqual(companyLinks('<a href="https://evil.com/career/test">Job</a><a href="/career/test/">Job</a>','https://vivasoftltd.com/career/'),['https://vivasoftltd.com/career/test/']);});
test('normalizes Ashby salary, schema locations, stable identity and invalid dates',()=>{const a=normalize({...source,provider:'Ashby',board:'example'},{id:'123',title:'Senior Engineer',descriptionHtml:'<p>React and TypeScript</p>',publishedAt:'invalid',jobUrl:'https://example.com/job/123',compensation:{scrapeableCompensationSalarySummary:'$100,000'},jobLocation:{address:{addressLocality:'Dhaka',addressCountry:'Bangladesh'}}});assert.equal(a.location,'Dhaka, Bangladesh');assert.equal(a.salary,'$100,000');assert.ok(a.skills.includes('React'));assert.ok(Number.isFinite(Date.parse(a.posted)));assert.equal(a.id,'Ashby-example-123');});
test('unsupported sources fail visibly',async()=>assert.rejects(()=>collect(source),/No supported interface/));
test('Bangladesh is not accepted as an Adzuna country',()=>assert.throws(()=>validateSource({company:'Adzuna',provider:'Adzuna',board:'bd'}),/Bangladesh/));

test('Tekarsh detection chooses the fixed public API, without enabling generic custom APIs',async()=>{const {detectSource}=await import('./sources');const detected=await detectSource(validateSource({company:'Tekarsh',url:'https://tekarsh.com/career'}));assert.equal(detected.provider,'Custom API');assert.equal(detected.board,'tekarsh');assert.throws(()=>validateSource({company:'Unsafe',provider:'Custom API',board:'arbitrary'}));});
test('job IDs remain stable across repeated normalization',()=>{const row={title:'Engineer',url:'https://example.com/jobs/42',description:'TypeScript'};assert.equal(normalize(source,row).id,normalize(source,row).id);});

test('write origin checks accept the actual local host and reject foreign origins',async()=>{const {sameOrigin}=await import('./request-origin');assert.equal(sameOrigin(new Request('http://localhost:3000/api/data',{headers:{host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000'}})),true);assert.equal(sameOrigin(new Request('http://localhost:3000/api/data',{headers:{host:'localhost:3000',origin:'https://evil.example'}})),false);});
